archeutils/urls.py
from django.urls import path
from . import arche_rdf_views

app_name = "archeutils"

urlpatterns = [
    path(
        "4arche/<app_name>",
        arche_rdf_views.relevante_classes,
        name="resolve_id_to_graph",
    ),
    path("resolve", arche_rdf_views.resolve_id_to_graph, name="resolve_id_to_graph"),
    path(
        "fbd/<app_name>/<model_name>",
        arche_rdf_views.fbd_arche_rdf,
        name="fbd_arche_rdf",
    ),
    path(
        "<app_name>/<model_name>/<pk>",
        arche_rdf_views.res_as_arche_graph,
        name="res_as_arche_graph",
    ),
    path(
        "<app_name>/<model_name>",
        arche_rdf_views.qs_as_arche_graph,
        name="qs_as_arche_graph",
    ),
]

archiv/urls.py
# generated by appcreator
from django.urls import path
from . import views
from . import stats_views

app_name = "archiv"
urlpatterns = [
    path("match-binary/", stats_views.MatchBinaryView.as_view(), name="match-binary"),
    path("actor/", views.ActorListView.as_view(), name="actor_browse"),
    path("actor/detail/<int:pk>", views.ActorDetailView.as_view(), name="actor_detail"),
    path("actor/create/", views.ActorCreate.as_view(), name="actor_create"),
    path("actor/edit/<int:pk>", views.ActorUpdate.as_view(), name="actor_edit"),
    path("actor/delete/<int:pk>", views.ActorDelete.as_view(), name="actor_delete"),
    path(
        "archaeologicalobject4dpuzzleid/",
        views.ArchaeologicalObject4DPuzzleIDListView.as_view(),
        name="archaeologicalobject4dpuzzleid_browse",
    ),
    path(
        "archaeologicalobject4dpuzzleid/detail/<int:pk>",
        views.ArchaeologicalObject4DPuzzleIDDetailView.as_view(),
        name="archaeologicalobject4dpuzzleid_detail",
    ),
    path(
        "archaeologicalobject4dpuzzleid/create/",
        views.ArchaeologicalObject4DPuzzleIDCreate.as_view(),
        name="archaeologicalobject4dpuzzleid_create",
    ),
    path(
        "archaeologicalobject4dpuzzleid/edit/<int:pk>",
        views.ArchaeologicalObject4DPuzzleIDUpdate.as_view(),
        name="archaeologicalobject4dpuzzleid_edit",
    ),
    path(
        "archaeologicalobject4dpuzzleid/delete/<int:pk>",
        views.ArchaeologicalObject4DPuzzleIDDelete.as_view(),
        name="archaeologicalobject4dpuzzleid_delete",
    ),
    path(
        "archaeologicalobjectid/",
        views.ArchaeologicalObjectIDListView.as_view(),
        name="archaeologicalobjectid_browse",
    ),
    path(
        "archaeologicalobjectid/detail/<int:pk>",
        views.ArchaeologicalObjectIDDetailView.as_view(),
        name="archaeologicalobjectid_detail",
    ),
    path(
        "archaeologicalobjectid/create/",
        views.ArchaeologicalObjectIDCreate.as_view(),
        name="archaeologicalobjectid_create",
    ),
    path(
        "archaeologicalobjectid/edit/<int:pk>",
        views.ArchaeologicalObjectIDUpdate.as_view(),
        name="archaeologicalobjectid_edit",
    ),
    path(
        "archaeologicalobjectid/delete/<int:pk>",
        views.ArchaeologicalObjectIDDelete.as_view(),
        name="archaeologicalobjectid_delete",
    ),
    path("archiveinf/", views.ArchiveINFListView.as_view(), name="archiveinf_browse"),
    path(
        "archiveinf/detail/<int:pk>",
        views.ArchiveINFDetailView.as_view(),
        name="archiveinf_detail",
    ),
    path(
        "archiveinf/create/",
        views.ArchiveINFCreate.as_view(),
        name="archiveinf_create",
    ),
    path(
        "archiveinf/edit/<int:pk>",
        views.ArchiveINFUpdate.as_view(),
        name="archiveinf_edit",
    ),
    path(
        "archiveinf/delete/<int:pk>",
        views.ArchiveINFDelete.as_view(),
        name="archiveinf_delete",
    ),
    path("autocad/", views.AutoCADListView.as_view(), name="autocad_browse"),
    path(
        "autocad/detail/<int:pk>",
        views.AutoCADDetailView.as_view(),
        name="autocad_detail",
    ),
    path("autocad/create/", views.AutoCADCreate.as_view(), name="autocad_create"),
    path("autocad/edit/<int:pk>", views.AutoCADUpdate.as_view(), name="autocad_edit"),
    path(
        "autocad/delete/<int:pk>",
        views.AutoCADDelete.as_view(),
        name="autocad_delete",
    ),
    path(
        "convolutecards/",
        views.ConvolutecardsListView.as_view(),
        name="convolutecards_browse",
    ),
    path(
        "convolutecards/detail/<int:pk>",
        views.ConvolutecardsDetailView.as_view(),
        name="convolutecards_detail",
    ),
    path(
        "convolutecards/create/",
        views.ConvolutecardsCreate.as_view(),
        name="convolutecards_create",
    ),
    path(
        "convolutecards/edit/<int:pk>",
        views.ConvolutecardsUpdate.as_view(),
        name="convolutecards_edit",
    ),
    path(
        "convolutecards/delete/<int:pk>",
        views.ConvolutecardsDelete.as_view(),
        name="convolutecards_delete",
    ),
    path("datenbase/", views.DatenbaseListView.as_view(), name="datenbase_browse"),
    path(
        "datenbase/detail/<int:pk>",
        views.DatenbaseDetailView.as_view(),
        name="datenbase_detail",
    ),
    path("datenbase/create/", views.DatenbaseCreate.as_view(), name="datenbase_create"),
    path(
        "datenbase/edit/<int:pk>",
        views.DatenbaseUpdate.as_view(),
        name="datenbase_edit",
    ),
    path(
        "datenbase/delete/<int:pk>",
        views.DatenbaseDelete.as_view(),
        name="datenbase_delete",
    ),
    path(
        "document4dpuzzleid/",
        views.Document4DPuzzleIDListView.as_view(),
        name="document4dpuzzleid_browse",
    ),
    path(
        "document4dpuzzleid/detail/<int:pk>",
        views.Document4DPuzzleIDDetailView.as_view(),
        name="document4dpuzzleid_detail",
    ),
    path(
        "document4dpuzzleid/create/",
        views.Document4DPuzzleIDCreate.as_view(),
        name="document4dpuzzleid_create",
    ),
    path(
        "document4dpuzzleid/edit/<int:pk>",
        views.Document4DPuzzleIDUpdate.as_view(),
        name="document4dpuzzleid_edit",
    ),
    path(
        "document4dpuzzleid/delete/<int:pk>",
        views.Document4DPuzzleIDDelete.as_view(),
        name="document4dpuzzleid_delete",
    ),
    path(
        "documenttypes/",
        views.DocumentTypesListView.as_view(),
        name="documenttypes_browse",
    ),
    path(
        "documenttypes/detail/<int:pk>",
        views.DocumentTypesDetailView.as_view(),
        name="documenttypes_detail",
    ),
    path(
        "documenttypes/create/",
        views.DocumentTypesCreate.as_view(),
        name="documenttypes_create",
    ),
    path(
        "documenttypes/edit/<int:pk>",
        views.DocumentTypesUpdate.as_view(),
        name="documenttypes_edit",
    ),
    path(
        "documenttypes/delete/<int:pk>",
        views.DocumentTypesDelete.as_view(),
        name="documenttypes_delete",
    ),
    path(
        "excavationobjectid/",
        views.ExcavationObjectIDListView.as_view(),
        name="excavationobjectid_browse",
    ),
    path(
        "excavationobjectid/detail/<int:pk>",
        views.ExcavationObjectIDDetailView.as_view(),
        name="excavationobjectid_detail",
    ),
    path(
        "excavationobjectid/create/",
        views.ExcavationObjectIDCreate.as_view(),
        name="excavationobjectid_create",
    ),
    path(
        "excavationobjectid/edit/<int:pk>",
        views.ExcavationObjectIDUpdate.as_view(),
        name="excavationobjectid_edit",
    ),
    path(
        "excavationobjectid/delete/<int:pk>",
        views.ExcavationObjectIDDelete.as_view(),
        name="excavationobjectid_delete",
    ),
    path(
        "excavationseasons/",
        views.ExcavationSeasonsListView.as_view(),
        name="excavationseasons_browse",
    ),
    path(
        "excavationseasons/detail/<int:pk>",
        views.ExcavationSeasonsDetailView.as_view(),
        name="excavationseasons_detail",
    ),
    path(
        "excavationseasons/create/",
        views.ExcavationSeasonsCreate.as_view(),
        name="excavationseasons_create",
    ),
    path(
        "excavationseasons/edit/<int:pk>",
        views.ExcavationSeasonsUpdate.as_view(),
        name="excavationseasons_edit",
    ),
    path(
        "excavationseasons/delete/<int:pk>",
        views.ExcavationSeasonsDelete.as_view(),
        name="excavationseasons_delete",
    ),
    path(
        "fielddrawing/",
        views.FielddrawingListView.as_view(),
        name="fielddrawing_browse",
    ),
    path(
        "fielddrawing/detail/<int:pk>",
        views.FielddrawingDetailView.as_view(),
        name="fielddrawing_detail",
    ),
    path(
        "fielddrawing/create/",
        views.FielddrawingCreate.as_view(),
        name="fielddrawing_create",
    ),
    path(
        "fielddrawing/edit/<int:pk>",
        views.FielddrawingUpdate.as_view(),
        name="fielddrawing_edit",
    ),
    path(
        "fielddrawing/delete/<int:pk>",
        views.FielddrawingDelete.as_view(),
        name="fielddrawing_delete",
    ),
    path("film/", views.FilmListView.as_view(), name="film_browse"),
    path("film/detail/<int:pk>", views.FilmDetailView.as_view(), name="film_detail"),
    path("film/create/", views.FilmCreate.as_view(), name="film_create"),
    path("film/edit/<int:pk>", views.FilmUpdate.as_view(), name="film_edit"),
    path("film/delete/<int:pk>", views.FilmDelete.as_view(), name="film_delete"),
    path(
        "finddrawing/",
        views.FinddrawingListView.as_view(),
        name="finddrawing_browse",
    ),
    path(
        "finddrawing/detail/<int:pk>",
        views.FinddrawingDetailView.as_view(),
        name="finddrawing_detail",
    ),
    path(
        "finddrawing/create/",
        views.FinddrawingCreate.as_view(),
        name="finddrawing_create",
    ),
    path(
        "finddrawing/edit/<int:pk>",
        views.FinddrawingUpdate.as_view(),
        name="finddrawing_edit",
    ),
    path(
        "finddrawing/delete/<int:pk>",
        views.FinddrawingDelete.as_view(),
        name="finddrawing_delete",
    ),
    path("findsheets/", views.FindsheetsListView.as_view(), name="findsheets_browse"),
    path(
        "findsheets/detail/<int:pk>",
        views.FindsheetsDetailView.as_view(),
        name="findsheets_detail",
    ),
    path(
        "findsheets/create/",
        views.FindsheetsCreate.as_view(),
        name="findsheets_create",
    ),
    path(
        "findsheets/edit/<int:pk>",
        views.FindsheetsUpdate.as_view(),
        name="findsheets_edit",
    ),
    path(
        "findsheets/delete/<int:pk>",
        views.FindsheetsDelete.as_view(),
        name="findsheets_delete",
    ),
    path(
        "fotoborndigital/",

bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

p4d/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from vocabs import api_views

router = routers.DefaultRouter()
router.register(r"metadata", api_views.MetadataViewSet)
router.register(r"skoslabels", api_views.SkosLabelViewSet)
router.register(r"skosnamespaces", api_views.SkosNamespaceViewSet)
router.register(r"skosconceptschemes", api_views.SkosConceptSchemeViewSet)
router.register(r"skoscollections", api_views.SkosCollectionViewSet)
router.register(r"skosconcepts", api_views.SkosConceptViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("admin/", admin.site.urls),
    path("archeutils/", include("archeutils.urls", namespace="archeutils")),
    path(
        "filechecker-rdf/",
        include("filechecker.fc_arche_urls", namespace="filechecker-rdf"),
    ),
    path("filechecker/", include("filechecker.urls", namespace="filechecker")),
    path("browsing/", include("browsing.urls", namespace="browsing")),
    path("netvis/", include("netvis.urls", namespace="netvis")),
    path("info/", include("infos.urls", namespace="info")),
    path("archiv/", include("archiv.urls", namespace="archiv")),
    path("qgisapp/", include("qgisapp.urls", namespace="qgisapp")),
    path("vocabs/", include("vocabs.urls", namespace="vocabs")),
    path("vocabs-ac/", include("vocabs.dal_urls", namespace="vocabs-ac")),
    path("", include("webpage.urls", namespace="webpage")),
]

webpage/urls.py
from django.urls import path
from . import views

app_name = "webpage"

urlpatterns = [
    path("imprint", views.ImprintView.as_view(), name="imprint"),
    path("", views.GenericWebpageView.as_view(), name="start"),
    path("accounts/login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="user_logout"),
    path("project-info/", views.project_info, name="project_info"),
    path("<slug:template>", views.GenericWebpageView.as_view(), name="staticpage"),
]

archiv/templates/archiv/convolutecards_detail.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %}{{ object.name }}{% endblock %}
{% block scriptHeader %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js"></script>
<script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
<script crossorigin src="https://unpkg.com/three@latest/build/three.min.js"></script>
<script crossorigin src="https://unpkg.com/@acdh/network-visualization@0/lib/network-visualization.umd.js"></script>
<script src="{% static 'netvis/js/netvis.js' %}"></script>
{% endblock %}
{% block content %}
<!-- <div class="container"> -->
<div class="card w-100">
  <div class="card-header">
    <div class="row">
      <div class="col-md-2">
        {% if object.get_prev %}
        <h2>
          <a href="{{ object.get_prev }}" title="previous">
            <i data-feather="chevron-left"></i>
          </a>
        </h2>
        {% endif %}
      </div>
      <div class="col-md-8">
        <h2 style="text-align: center;">
          <small><a href="{{ object.get_listview_url }}" title="back to listview"><small>{{ class_name }}</small></a></small>
          {{ object }}
          {% if user.is_authenticated %}
            <a href="{{ object.get_edit_url }}" title="edit">
              <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </a>
            <a href="{{ object.get_delete_url }}" title="delete">
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </a>
          {% endif %}
          {% if 'archeutils' in APPS %}
          <a href="{% url 'archeutils:res_as_arche_graph' app_name=app_name model_name=class_name|lower pk=object.id %}" title="As ARCHE-RDF">
            <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
          </a>
          {% endif%}
        </h2>
      </div>
      <div class="col-md-2">
        <h2>
          {% if object.get_next %}
          <a href="{{ object.get_next }}" style="float:right" title="next">
            <i data-feather="chevron-right"></i>
          </a>
        </h2>
        {% endif %}
      </div>
      <div class="col-md-2">
        <h2>
          {% if object.get_next %}
          <a href="{{ object.get_next }}" style="float:right" title="next">
            <i data-feather="chevron-right"></i>
          </a>
        </h2>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="card-body">
    {% block custom %}
    <legend>Basic Information </legend>
    <div class="row">

        <div class="col-md-6">
            <table class="table table-responsive table-hover">
              <tr>
                <th>preview</th>
                <td>
                  {% if object.access.pref_label == 'public' %}
                    <img src="{{ arche_thumb }}" alt="..." class="img-thumbnail" />
                  {% else %}
                    restricted access
                  {% endif %}
                </td>
              <tr>
              {% for x in object.field_dict %}
              {% if x.value %}
              {% if user.is_authenticated %}
                <th>
                  {% if x.help_text %}
                  <abbr title="{{ x.help_text }}">{{ x.verbose_name }}</abbr>
                  {% else %}
                  {{ x.verbose_name }}
                  {% endif %}
                </th>
                <td>
                  {% if x.f_type == 'M2M' %}
                  {% for y in x.value %}
                  <li>
                    <a href="{{ y.get_absolute_url }}">{{ y }}</a>
                  </li>
                  {% endfor %}
                  {% elif  x.f_type == 'FK' %}
                  <a href="{{ x.value.get_absolute_url }}">{{ x.value }}</a>
                  {% elif  x.f_type == 'FK' %}
                  <a href="{{ x.value.get_absolute_url }}">{{ x.value }}</a>
                  {% elif  x.f_type == 'REVRESE_RELATION' %}
                  {% for y in x.value %}
                  <li>
                    <a href="{{ y.get_absolute_url }}">{{ y }}</a>
                  </li>
                  {% endfor %}

                  {% elif  x.f_type == 'SIMPLE' %}
                  {{ x.value }}
                  {% endif %}
                </td>
              </tr>
              {% elif not x.extra_fields or x.extra_fields.is_public %}
              {% if x.verbose_name != "The original data" %}
              <tr>
                <th>
                  {% if x.help_text %}
                  <abbr title="{{ x.help_text }}">{{ x.verbose_name }}</abbr>
                  {% else %}
                  {{ x.verbose_name }}
                  {% endif %}
                </th>
                <td>
                  {% if x.f_type == 'M2M' %}
                  {% for y in x.value %}
                  <li>
                    <a href="{{ y.get_absolute_url }}">{{ y }}</a>
                  </li>
                  {% endfor %}
                  {% elif  x.f_type == 'FK' %}
                  {% if x.verbose_name == 'Copyright' %}
                  <a href="{{ x.value.get_absolute_url }}">{{ x.value|upper }}</a>
                  {% else %}
                  <a href="{{ x.value.get_absolute_url }}">{{ x.value }}</a>
                  {% endif %}
                  {% elif  x.f_type == 'FK' %}
                  <a href="{{ x.value.get_absolute_url }}">{{ x.value }}</a>
                  {% elif  x.f_type == 'REVRESE_RELATION' %}
                  {% for y in x.value %}
                  <li>
                    <a href="{{ y.get_absolute_url }}">{{ y }}</a>
                  </li>
                  {% endfor %}

                  {% elif  x.f_type == 'SIMPLE' %}
                  {{ x.value }}
                  {% endif %}
                </td>
              </tr>
              {% endif %}
              {% endif %}
              {% endif %}
              {% endfor %}
            </table>
        </div>
        <div class="col-md-6">
            <div id="visualization" style="position: relative; height: 700px; background: #fafafa;"></div>
            <script type="text/javascript">
              showGraph("{% url 'netvis:graph' app_name=app_name model_name=class_name|lower pk=object.id %}", "visualization")
            </script>
            {% if object.access.pref_label == 'public' %}
              <div id="openseadragon-photo" style="height: 350px;"></div>
              <script src="https://cdnjs.cloudflare.com/ajax/libs/openseadragon/2.4.1/openseadragon.min.js"></script>
              <script type="text/javascript">
                  var viewer = OpenSeadragon({
                      id: "openseadragon-photo",
                      protocol: "http://iiif.io/api/image",
                      prefixUrl: "https://cdnjs.cloudflare.com/ajax/libs/openseadragon/2.4.1/images/",
                      sequenceMode : true,
                      showReferenceStrip: true,
                      tileSources: ["{{ arche_id }}?PARAM=info.json&format=iiif"]
                  });
              </script>
              {% else %}
                restricted access
              {% endif %}
        </div>

    </div>


  </div>
</div>
{% endblock custom %}
{% endblock %}

archiv/templates/archiv/foto_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block title %}Foto: {{ object }}{% endblock %}
{% block scriptHeader %}
{% endblock %}
{% block content %}
<div class="panel panel-body">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Digital Archive</li>
    <li class="breadcrumb-item"><a href="{% url 'webpage:staticpage' template='explore' %}">Explore TD resources</a></li>
    <li class="breadcrumb-item"><a href="{% url 'browsing:browse_fotos' %}">Search all photos</a></li>
    <li class="breadcrumb-item">photo {{ object.document_id }}</a></li>
  </ol>
    <div class="panel panel-default procustom-panel-create">
        <div class="panel-heading procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                    <h2>
                        <a href="{% url 'archiv:foto-detail' pk=object.get_prev %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true" title="previous area"></span></a>
                    </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                       <small>photo id: </small>{{ object.document_id }}
                    </h1>
                </div>
                <div class="col-md-2">
                {% if object.get_next %}
                    <h2>
                        <a href="{% url 'archiv:foto-detail' pk=object.get_next %}" style="float:right"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true" title="next area"></span></a>
                    </h2>
                {% endif %}
                </div>
            </div>
        </div>
        <div class="panel-body" style="text-align:center">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-hover table-condensed">
                        <tr>
                            <th>file name</th>
                            <td>{{ object.composed_id }}</td>
                        </tr>
                        <tr>
                            <th>document id</th>
                            <td>{{ object.document_id }}</td>
                        </tr>
                        <tr>
                            <th>photo title</th>
                            <td>{{ object.photo_title }}</td>
                        </tr>
                        <tr>
                            <th>film number</th>
                            <td>{{ object.film_number }}</td>
                        </tr>
                        <tr>
                            <th>film id</th>
                            <td>{{ object.film_id }}</td>
                        </tr>
                        <tr>
                            <th>photo number</th>
                            <td>{{ object.photo_number }}</td>
                        </tr>
                        <tr>
                            <th>digital phototype</th>
                            <td>{{ object.digital_photo_type }}</td>
                        </tr>
                        <tr>
                            <th>photo format</th>
                            <td>{{ object.foto_format }}</td>
                        </tr>
                        <tr>
                            <th>photographer</th>
                            <td>{{ object.photographer }}</td>
                        </tr>
                        <tr>
                            <th>original filmfolder</th>
                            <td>{{ object.original_film_folder }}</td>
                        </tr>
                        <tr>
                            <th>photo type</th>
                            <td>{{ object.foto_type }}</td>
                        </tr>
                        <tr>
                            <th>content type</th>
                            <td>{% for x in object.content_type.all %} {{ x }} <br/> {% endfor %}</td>
                        </tr>
                        <tr>
                            <th>site</th>
                            <td>{{ object.site }}</td>
                        </tr>
                        <tr>
                            <th>year</th>
                            <td>{{ object.year }}</td>
                        </tr>
                        <tr>
                            <th>archaeological object</th>
                            <td>{% for x in object.archobject.all %} {{ x }} <br/> {% endfor %}</td>
                        </tr>
                        <tr>
                            <th>excavation object</th>
                            <td>
                                {% for x in object.exobject.all %}
                                    <a href="{% url 'archobs:exobject-detail' pk=x.id %}">{{ x }}</a> <br/> {% endfor %}</td>
                        </tr>
                        <tr>
                            <th>scale</th>
                            <td>{{ object.scale }}</td>
                        </tr>
                        <tr>
                            <th>metadata creation date</th>
                            <td>{{ object.metadata_creation_date }}</td>
                        </tr>
                        <tr>
                            <th>metadata comment</th>
                            <td>{{ object.metadata_comment }}</td>
                        </tr>
                        <tr>
                            <th>metadata creator</th>
                            <td>{% for x in object.metadata_creator.all %} {{ x }} <br/> {% endfor %}</td>
                        </tr>
                        <tr>
                            <th>scan</th>
                            <td>{% for x in object.scan.all %} <a href="{% url 'images:scan_detail' pk=x.id %}">{{ x }}</a> <br/> {% endfor %}</td>
                        </tr>
                    </table>
                </div>
                <div class="col-md-6">
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary" id="zoom-in">Zoom In</button>
                        <button type="button" class="btn btn-primary" id="home">Default</button>
                        <button type="button" class="btn btn-primary" id="zoom-out">Zoom Out</button>
                        <button type="button" class="btn btn-primary" id="full-page">Full Sceen</button>
                    </div>
                    <div id="openseadragon1" style="width: 100%; height: 400px"></div>
                    <script src="{% static 'images/openseadragon/openseadragon.min.js' %}"></script>
                    <script type="text/javascript">
                        var viewer = OpenSeadragon({
                            id: "openseadragon1",
                            tileSources: "{{ object.iiifjson }}",
                            zoomInButton:   "zoom-in",
                            zoomOutButton:  "zoom-out",
                            homeButton:     "home",
                            fullPageButton: "full-page",
                        });
                    </script>
                </div>
        </div>
    </div>
    </div>
    <div id="map"/>
</div>
{% endblock %}

archiv/templates/archiv/match_stats.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} Matching Binaries stats {% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">Matching Binaries stats</h1>
        </div>
        <div class="card-body">
            <div>
                <table class="table" id="example">
                  <thead>
                  <tr>
                    {% for x in table_head %}
                      <th>{{ x }}</th>
                    {% endfor %}
                  <tr/>
                  </thead>
                  <tbody>
                  {% for x in table_body %}
                  <tr>
                    {% for i in x %}
                      <td>{{ i }}</td>
                    {% endfor %}
                  </tr>
                  {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>
<!-- <script type="text/javascript">
  $(document).ready(function() {
    $('#example').DataTable();
} );
</script> -->

{% endblock %}