4dpuzzle/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from places.apis_views import PlaceViewSet
from bib.api_views import BookViewSet

from vocabs import api_views

router = routers.DefaultRouter()
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'Book', BookViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^sparql/', include('sparql.urls', namespace='sparql')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'places/', include('places.urls', namespace='places')),
    url(r'^bib/', include('bib.urls', namespace='bib')),
    url(r'^images/', include('images.urls', namespace='images')),
    url(r'^archobs-json/', include('archobs.api_urls', namespace='archobs-json')),
    url(r'^archobs-dal/', include('archobs.dal_urls', namespace='archobs-dal')),
    url(r'^archobs/', include('archobs.urls', namespace='archobs')),
    url(r'^archiv/', include('archiv.urls', namespace='archiv')),
    url(r'^', include('webpage.urls', namespace='webpage')),
]

bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ScanListView.as_view(), name='scan_list'),
    url(r'^(?P<pk>[0-9]+)$', views.ScanDetailView.as_view(), name='scan_detail'),
    # url(r'^create/$', views.ScanCreate.as_view(), name='image_create'),
    # url(r'^update/(?P<pk>[0-9]+)$', views.ScanUpdate.as_view(), name='image_update'),
]

p4d/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from vocabs import api_views

router = routers.DefaultRouter()
router.register(r"metadata", api_views.MetadataViewSet)
router.register(r"skoslabels", api_views.SkosLabelViewSet)
router.register(r"skosnamespaces", api_views.SkosNamespaceViewSet)
router.register(r"skosconceptschemes", api_views.SkosConceptSchemeViewSet)
router.register(r"skoscollections", api_views.SkosCollectionViewSet)
router.register(r"skosconcepts", api_views.SkosConceptViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("admin/", admin.site.urls),
    path("archeutils/", include("archeutils.urls", namespace="archeutils")),
    path(
        "filechecker-rdf/",
        include("filechecker.fc_arche_urls", namespace="filechecker-rdf"),
    ),
    path("filechecker/", include("filechecker.urls", namespace="filechecker")),
    path("browsing/", include("browsing.urls", namespace="browsing")),
    path("netvis/", include("netvis.urls", namespace="netvis")),
    path("info/", include("infos.urls", namespace="info")),
    path("archiv/", include("archiv.urls", namespace="archiv")),
    path("qgisapp/", include("qgisapp.urls", namespace="qgisapp")),
    path("vocabs/", include("vocabs.urls", namespace="vocabs")),
    path("vocabs-ac/", include("vocabs.dal_urls", namespace="vocabs-ac")),
    path("", include("webpage.urls", namespace="webpage")),
]

images/models.py
import os
from django.db import models
from django.conf import settings
from places.models import Person
from vocabs.models import SkosConcept

try:
    base_url = settings.IIIF_BASE
except:
    base_url = "https://4dpuzzle-iiif.acdh.oeaw.ac.at"

IIIF_PATH = "{}{}".format(base_url, os.path.basename(settings.BASE_DIR))
FILE_EXTENSION_CHOICES = (
    ('.tif', 'tif'),
    ('.jpg', '.jpg'),
)


class ServerPath(models.Model):
    name = models.CharField(default=IIIF_PATH, blank=True, max_length=250)

    def __str__(self):
        return "{}".format(self.name)


class Image(models.Model):
    path = models.ForeignKey(ServerPath, blank=True, null=True)
    directory = models.CharField(blank=True, max_length=250)
    filename = models.CharField(blank=True, max_length=250)
    file_extension = models.CharField(
        blank=True, max_length=20, choices=FILE_EXTENSION_CHOICES, default='.jpg')

    class Meta:
        abstract = True

    def get_next(self):
        next = Image.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Image.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return prev.first().id
        return False

    def save(self, *args, **kwargs):
        if self.path is None:
            temp_path, _ = ServerPath.objects.get_or_create(name=IIIF_PATH)
            self.path = temp_path
        else:
            pass
        super(Image, self).save(*args, **kwargs)

    @property
    def full_path(self):
        if self.directory == "":
            return "{}/{}/info.json".format(self.path, self.filename)
        else:
            return "{}{}/{}/info.json".format(self.path, self.directory, self.filename)

    def __str__(self):
        return self.full_path

    @property
    def iiif_endpoint(self):
        if self.directory == "":
            return "{}/{}".format(self.path, self.filename)
        else:
            return "{}{}/{}".format(self.path, self.directory, self.filename)

    def __str__(self):
        return self.full_path


class Scan(Image):
    creator_scan = models.ManyToManyField(Person, blank=True, related_name='creator_scan')
    scan_date = models.DateField(blank=True, null=True)
    equipment = models.ForeignKey(SkosConcept, blank=True, null=True)
    resolution = models.CharField(max_length=300, blank=True, null=True)
    scan_type = models.ForeignKey(SkosConcept, blank=True, null=True, related_name="scan_type")

    def get_next(self):
        next = Scan.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Scan.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return prev.first().id
        return False

    def save(self, *args, **kwargs):
        if self.path is None:
            temp_path, _ = ServerPath.objects.get_or_create(name=IIIF_PATH)
            self.path = temp_path
        else:
            pass
        super(Scan, self).save(*args, **kwargs)

    @property
    def full_path(self):
        if self.directory == "":
            return "{}/{}/info.json".format(self.path, self.filename)
        else:
            return "{}{}/{}/info.json".format(self.path, self.directory, self.filename)

    def __str__(self):
        return self.full_path

    @property
    def iiif_endpoint(self):
        if self.directory == "":
            return "{}/{}".format(self.path, self.filename)
        else:
            return "{}{}/{}".format(self.path, self.directory, self.filename)

    def __str__(self):
        return self.full_path

images/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import Image, Scan


class ScanDetailView(DetailView):
    model = Scan
    template_name = 'images/scan_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ScanDetailView, self).get_context_data(**kwargs)
        # try:
        #     context["next_entry"] = Scan.objects.filter(id__gt=int(self.kwargs['pk']))[0].pk
        # except:
        #     context["next_entry"] = None
        # try:
        #     prev = [x.id for x in Scan.objects.filter(id__lt=int(self.kwargs['pk']))][-1]
        # except:
        #     prev = Scan.objects.get(id=self.kwargs['pk'])
        # try:
        #     Scan.objects.get(id=int(prev)-1)
        #     context["previous_entry"] = prev
        # except:
        #     context["previous_entry"] = None

        return context

    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super(ScanDetailView, self).dispatch(*args, **kwargs)


class ScanListView(ListView):
    model = Scan
    template_name = 'images/image_list.html'

    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super(ScanListView, self).dispatch(*args, **kwargs)

images/templates/images/image_list.html
{% extends "webpage/base.html" %}

{% block content %}

<div class="container">
<div class="panel panel-default procustom-panel-list">
    <div class="panel-heading procustom-panel-heading">
        <h1>Images </h1>
        <div>
            {% if user.is_authenticated %}
                <a class="btn btn-primary" href="#" role="button">create new Image</a>
            {% endif %}
      </div>
      <br>
    </div>
    <div class="panel-body procustom-panel-body">
        <table class="table table-bordered table-hover">
            <tr>
                <th>Image</th>
            </tr>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'images:image_detail' pk=object.id %}">{{ object }}</a>
                    </td>
                </tr>
            {% endfor %}
        </table>

    </div>
</div>
</div>


{% endblock %}

images/templates/images/scan_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %} {{ object.id }} {% endblock %}
{% block content %}

<div class="panel panel-default procustom-panel-create">
        <div class="panel-heading procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                    <h2>
                        <a href="{% url 'images:scan_detail' pk=object.get_prev %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true" title="previous area"></span></a>
                    </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                       <small>scan of: </small>{{ object.filename }}
                    </h1>
                </div>
                <div class="col-md-2">
                {% if object.get_next %}
                    <h2>
                        <a href="{% url 'images:scan_detail' pk=object.get_next %}" style="float:right"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true" title="next area"></span></a>
                    </h2>
                {% endif %}
                </div>
            </div>
        </div>
        <div class="panel-body" style="text-align:center">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-hover table-condensed">
                        <tr>
                            <th>creator_scan</th>
                            <td>{% for x in object.creator_scan.all %}{{ x }}<br/> {% endfor %}</td>
                        </tr>
                        <tr>
                            <th>scan_type</th>
                            <td>{{ object.scan_type }}</td>
                        </tr>
                        <tr>
                            <th>scan_date</th>
                            <td>{{ object.scan_date }}</td>
                        </tr>
                        <tr>
                            <th>equipment</th>
                            <td>{{ object.equipment }}</td>
                        </tr>
                        <tr>
                            <th>resolution</th>
                            <td>{{ object.resolution }}</td>
                        </tr>
                        <tr>
                            <th>IIIF-Json</th>
                            <td><a href="{{ object.full_path }}">{{ object.full_path }}</td>
                        </tr>
                        <tr>
                            <th>related objects</th>
                            <td>
                                {% for x in object.fielddrawing_set.all %}
                                    <a href="{% url 'archiv:fielddrawing-detail' pk=x.id %}">{{ x }}</a><br/>
                                {% endfor %}
                                {% for x in object.foto_set.all %}
                                    <small>{{ x.foto_type }} </small><a href="{% url 'archiv:foto-detail' pk=x.id %}">{{ x }}</a><br/>
                                {% endfor %}
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="col-md-6">
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary" id="zoom-in">Zoom In</button>
                        <button type="button" class="btn btn-primary" id="home">Default</button>
                        <button type="button" class="btn btn-primary" id="zoom-out">Zoom Out</button>
                        <button type="button" class="btn btn-primary" id="full-page">Full Sceen</button>
                    </div>
                    <div id="openseadragon1" style="width: 100%; height: 400px"></div>
                    <script src="{% static 'images/openseadragon/openseadragon.min.js' %}"></script>
                    <script type="text/javascript">
                        var viewer = OpenSeadragon({
                            id: "openseadragon1",
                            tileSources: "{{ object }}",
                            zoomInButton:   "zoom-in",
                            zoomOutButton:  "zoom-out",
                            homeButton:     "home",
                            fullPageButton: "full-page",
                        });
                    </script>
                </div>
            </div>
        </div>
</div>

{% endblock content %}

images/templates/images/scan_list.html
{% extends "webpage/base.html" %}

{% block content %}

<div class="container">
<div class="panel panel-default procustom-panel-list">
    <div class="panel-heading procustom-panel-heading">
        <h1>Images </h1>
        <div>
            {% if user.is_authenticated %}
                <a class="btn btn-primary" href="#" role="button">create new Image</a>
            {% endif %}
      </div>
      <br>
    </div>
    <div class="panel-body procustom-panel-body">
        <table class="table table-bordered table-hover">
            <tr>
                <th>Image</th>
            </tr>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{% url 'images:scan_detail' pk=object.id %}">{{ object }}</a>
                    </td>
                </tr>
            {% endfor %}
        </table>

    </div>
</div>
</div>


{% endblock %}