bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

p4d/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from vocabs import api_views

router = routers.DefaultRouter()
router.register(r"metadata", api_views.MetadataViewSet)
router.register(r"skoslabels", api_views.SkosLabelViewSet)
router.register(r"skosnamespaces", api_views.SkosNamespaceViewSet)
router.register(r"skosconceptschemes", api_views.SkosConceptSchemeViewSet)
router.register(r"skoscollections", api_views.SkosCollectionViewSet)
router.register(r"skosconcepts", api_views.SkosConceptViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("admin/", admin.site.urls),
    path("archeutils/", include("archeutils.urls", namespace="archeutils")),
    path(
        "filechecker-rdf/",
        include("filechecker.fc_arche_urls", namespace="filechecker-rdf"),
    ),
    path("filechecker/", include("filechecker.urls", namespace="filechecker")),
    path("browsing/", include("browsing.urls", namespace="browsing")),
    path("netvis/", include("netvis.urls", namespace="netvis")),
    path("info/", include("infos.urls", namespace="info")),
    path("archiv/", include("archiv.urls", namespace="archiv")),
    path("qgisapp/", include("qgisapp.urls", namespace="qgisapp")),
    path("vocabs/", include("vocabs.urls", namespace="vocabs")),
    path("vocabs-ac/", include("vocabs.dal_urls", namespace="vocabs-ac")),
    path("", include("webpage.urls", namespace="webpage")),
]

vocabs/urls.py
from django.urls import path
from . import views

app_name = "vocabs"


urlpatterns = [
    path("", views.SkosConceptListView.as_view(), name="skosconcept_list"),
    path("concepts/browse/", views.SkosConceptListView.as_view(), name="browse_vocabs"),
    path("<int:pk>", views.SkosConceptDetailView.as_view(), name="skosconcept_detail"),
    path("create/", views.SkosConceptCreate.as_view(), name="skosconcept_create"),
    path(
        "update/<int:pk>",
        views.SkosConceptUpdate.as_view(),
        name="skosconcept_update",
    ),
    path(
        "delete/<int:pk>",
        views.SkosConceptDelete.as_view(),
        name="skosconcept_delete",
    ),
    path("scheme/", views.SkosConceptSchemeListView.as_view(), name="browse_schemes"),
    path(
        "scheme/<int:pk>",
        views.SkosConceptSchemeDetailView.as_view(),
        name="skosconceptscheme_detail",
    ),
    path(
        "scheme/create/",
        views.SkosConceptSchemeCreate.as_view(),
        name="skosconceptscheme_create",
    ),
    path(
        "scheme/update/<int:pk>",
        views.SkosConceptSchemeUpdate.as_view(),
        name="skosconceptscheme_update",
    ),
    path(
        "scheme/delete/<int:pk>",
        views.SkosConceptSchemeDelete.as_view(),
        name="skosconceptscheme_delete",
    ),
    path("label/", views.SkosLabelListView.as_view(), name="browse_skoslabels"),
    path(
        "label/<int:pk>", views.SkosLabelDetailView.as_view(), name="skoslabel_detail"
    ),
    path("label/create/", views.SkosLabelCreate.as_view(), name="skoslabel_create"),
    path(
        "label/update/<int:pk>",
        views.SkosLabelUpdate.as_view(),
        name="skoslabel_update",
    ),
    path(
        "skoslabel/delete/<int:pk>",
        views.SkosLabelDelete.as_view(),
        name="skoslabel_delete",
    ),
    path("vocabs-download/", views.SkosConceptDL.as_view(), name="vocabs-download"),
    path("metadata/", views.MetadataListView.as_view(), name="metadata"),
    path(
        "metadata/<int:pk>",
        views.MetadataDetailView.as_view(),
        name="metadata_detail",
    ),
    path("metadata/create/", views.MetadataCreate.as_view(), name="metadata_create"),
    path(
        "metadata/update/<int:pk>",
        views.MetadataUpdate.as_view(),
        name="metadata_update",
    ),
    path(
        "metadata/delete/<int:pk>",
        views.MetadataDelete.as_view(),
        name="metadata_delete",
    ),
    path(
        "collection/",
        views.SkosCollectionListView.as_view(),
        name="browse_skoscollections",
    ),
    path(
        "collection/<int:pk>",
        views.SkosCollectionDetailView.as_view(),
        name="skoscollection_detail",
    ),
    path(
        "collection/create/",
        views.SkosCollectionCreate.as_view(),
        name="skoscollection_create",
    ),
    path(
        "collection/update/<int:pk>",
        views.SkosCollectionUpdate.as_view(),
        name="skoscollection_update",
    ),
    path(
        "collection/delete/<int:pk>",
        views.SkosCollectionDelete.as_view(),
        name="skoscollection_delete",
    ),
]

vocabs/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django_tables2 import RequestConfig
from .models import SkosConcept, SkosConceptScheme, SkosLabel, SkosCollection, Metadata
from .forms import (
    MetadataForm,
    SkosCollectionForm, SkosCollectionFormHelper, SkosConceptForm, SkosConceptFormHelper, SkosConceptSchemeForm, SkosConceptSchemeFormHelper, SkosLabelForm, SkosLabelFormHelper
)
from .tables import (
    SkosCollectionTable,
    SkosConceptSchemeTable,
    SkosConceptTable,
    SkosLabelTable,
)
from .filters import (
    SkosConceptListFilter,
    SkosConceptSchemeListFilter,
    SkosLabelListFilter,
    SkosCollectionListFilter,
)
from browsing.browsing_utils import GenericListView, BaseCreateView, BaseUpdateView
from .rdf_utils import graph_construct_qs
from django.http import HttpResponse

import time
import datetime


#####################################################
#   Metadata
#####################################################


class MetadataListView(ListView):
    model = Metadata
    template_name = "vocabs/metadata_list.html"

    def get_context_data(self, **kwargs):
        context = super(MetadataListView, self).get_context_data(**kwargs)
        context["topConcepts"] = SkosConcept.objects.filter(top_concept=True)
        return context


class MetadataDetailView(DetailView):
    model = Metadata
    template_name = "vocabs/metadata_detail.html"

    def get_context_data(self, **kwargs):
        context = super(MetadataDetailView, self).get_context_data(**kwargs)
        context["topConcepts"] = SkosConcept.objects.filter(top_concept=True)
        return context


class MetadataCreate(BaseCreateView):
    model = Metadata
    form_class = MetadataForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetadataCreate, self).dispatch(*args, **kwargs)


class MetadataUpdate(BaseUpdateView):
    model = Metadata
    form_class = MetadataForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetadataUpdate, self).dispatch(*args, **kwargs)


class MetadataDelete(DeleteView):
    model = Metadata
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("vocabs:metadata")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetadataDelete, self).dispatch(*args, **kwargs)


#####################################################
#   SkosCollection
#####################################################


class SkosCollectionListView(GenericListView):
    model = SkosCollection
    table_class = SkosCollectionTable
    filter_class = SkosCollectionListFilter
    formhelper_class = SkosCollectionFormHelper
    init_columns = [
        "id",
        "name",
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosCollectionListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [
            x for x in self.get_all_cols() if x not in self.init_columns
        ]
        context["togglable_colums"] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(
            self.request, paginate={"page": 1, "per_page": self.paginate_by}
        ).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosCollectionDetailView(DetailView):
    model = SkosCollection
    template_name = "vocabs/skoscollection_detail.html"


class SkosCollectionCreate(BaseCreateView):
    model = SkosCollection
    form_class = SkosCollectionForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosCollectionCreate, self).dispatch(*args, **kwargs)


class SkosCollectionUpdate(BaseUpdateView):
    model = SkosCollection
    form_class = SkosCollectionForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosCollectionUpdate, self).dispatch(*args, **kwargs)


class SkosCollectionDelete(DeleteView):
    model = SkosCollection
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("vocabs:browse_skoscollections")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosCollectionDelete, self).dispatch(*args, **kwargs)


#####################################################
#   Concept
#####################################################


class SkosConceptListView(GenericListView):
    model = SkosConcept
    table_class = SkosConceptTable
    filter_class = SkosConceptListFilter
    formhelper_class = SkosConceptFormHelper
    init_columns = [
        "id",
        "pref_label",
        "broader_concept",
    ]
    enable_merge = True


class SkosConceptDetailView(DetailView):
    model = SkosConcept
    template_name = "vocabs/skosconcept_detail.html"


class SkosConceptCreate(BaseCreateView):
    model = SkosConcept
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptCreate, self).dispatch(*args, **kwargs)


class SkosConceptUpdate(BaseUpdateView):
    model = SkosConcept
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptUpdate, self).dispatch(*args, **kwargs)


class SkosConceptDelete(DeleteView):
    model = SkosConcept
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("vocabs:browse_vocabs")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptDelete, self).dispatch(*args, **kwargs)


#####################################################
#   ConceptScheme
#####################################################


class SkosConceptSchemeListView(GenericListView):
    model = SkosConceptScheme
    table_class = SkosConceptSchemeTable
    filter_class = SkosConceptSchemeListFilter
    formhelper_class = SkosConceptSchemeFormHelper
    init_columns = [
        "id",
        "dc_title",
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [
            x for x in self.get_all_cols() if x not in self.init_columns
        ]
        context["togglable_colums"] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(
            self.request, paginate={"page": 1, "per_page": self.paginate_by}
        ).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosConceptSchemeDetailView(DetailView):
    model = SkosConceptScheme
    template_name = "vocabs/skosconceptscheme_detail.html"

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeDetailView, self).get_context_data(**kwargs)
        context["concepts"] = SkosConcept.objects.filter(scheme=self.kwargs.get("pk"))
        return context


class SkosConceptSchemeCreate(BaseCreateView):
    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeCreate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeUpdate(BaseUpdateView):
    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeUpdate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeDelete(DeleteView):
    model = SkosConceptScheme
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("vocabs:browse_schemes")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeDelete, self).dispatch(*args, **kwargs)


###################################################
# SkosLabel
###################################################


class SkosLabelListView(GenericListView):
    model = SkosLabel
    table_class = SkosLabelTable
    filter_class = SkosLabelListFilter
    formhelper_class = SkosLabelFormHelper
    init_columns = [
        "id",
        "name",
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosLabelListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [
            x for x in self.get_all_cols() if x not in self.init_columns
        ]
        context["togglable_colums"] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()

vocabs/templates/vocabs/confirm_delete.html
{% extends "vocabs/plain_for_delete.html" %}
{% block content %}
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
            <h3 class="modal-title">Confirm delete</h3>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="post">{% csrf_token %}
                    <h4>Are you sure you want to delete :<br /> <strong>{{ object }}</strong> ?</h4><br />
                    <a href="javascript:history.back()"><input class="btn btn-default" type="button" value="cancel"/></a>
                    <input  class="btn btn-danger" type="submit" value="yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
    <script type="text/javascript">
        $(window).load(function(){
            $('#myModal').modal('show');
        });
    </script>
{% endblock scripts %}

vocabs/templates/vocabs/generic_list.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}See all {{ object.classname }}{% endblock %}
{% block scriptHeader %}{% endblock %}
{% block content %}
<div class="container">
<div class="panel panel-default procustom-panel-list">
    <div class="panel-heading procustom-panel-heading">
        <h1>{% block list_title %}{% endblock %}</h1>
        {% block create_button %}{% endblock %}
        <br />
    </div>
    <div class="panel-body procustom-panel-body">
        <div class="row">
            <div class="col-md-4">
                {% load django_tables2 crispy_forms_tags %}
                {% crispy filter.form filter.form.helper %}
                {% block reset_button %}
                {% endblock %}
            </div>
            <div class="col-md-8">
                {% render_table table %}
            </div>
        </div>
    </div>
</div>
</div>
{% block customScripts %}{% endblock %}
{% endblock %}

vocabs/templates/vocabs/metadata_list.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
{% if object_list %}
{% for x in object_list %}
<div class="card">
    <div class="card-header">
        <h1 style="text-align: center;">Metadata {{ x.title }}
        {% if user.is_authenticated %}
            <small>
                <a href="{% url 'vocabs:metadata_update' pk=x.id %}">
                    <i class="feather-32" data-feather="edit" title="edit"></i>
                </a>
            </small>
                |
            <small>
                <a href="{% url 'vocabs:metadata_delete' pk=x.id %}">
                    <i class="feather-32" data-feather="trash" title="delete"></i>
                </a>
            </small>
         {% endif %}
        </h1>
    </div>
        <table class="table">
        <tr>
        	<th class="w-25">Title</th>
        	<td>{{x.title}}</td>
        </tr>
        <tr>
        	<th>Indentifier</th>
        	<td>{{x.indentifier}}</td>
        </tr>
        <tr>
        	<th>Description</th>
        	<td>{{x.description}}</td>
        </tr>
        <tr>
        	<th>Description language</th>
        	<td>{{x.description_lang}}</td>
        </tr>
        <tr>
        	<th>Language</th>
        	<td>
        	{% if x.language %}
        	{% for language in x.language_as_list %}
    		<li>{{ language }}</li>
			{% endfor %}
			{% endif %}
			</td>
        </tr>
        <tr>
        	<th>Version</th>
        	<td>{{x.version}}</td>
        </tr>
        <tr>
        	<th>Creator</th>
        	<td>
            {% if x.creator %}
            {% for creator in x.creator_as_list %}
            <li>{{ creator }}</li>
            {% endfor %}
            {% endif %}    
            </td>
        </tr>
        <tr>
        	<th>Contributor</th>
        	<td>
            {% if x.contributor %}
            {% for contributor in x.contributor_as_list %}
            <li>{{ contributor }}</li>
            {% endfor %}
            {% endif %} 
            </td>
        </tr>
        <tr>
        	<th>Subject</th>
        	<td>
        	{% if x.subject %}
        	{% for subject in x.subject_as_list %}
    		<li>{{ subject }}</li>
			{% endfor %}
			{% endif %}
			</td>
        </tr>
        <tr>
        	<th>Owner</th>
        	<td>{{x.owner}}</td>
        </tr>
        <tr>
        	<th>License</th>
        	<td>{{x.license}}</td>
        </tr>
        <tr>
        	<th>Date created</th>
        	<td>{{x.date_created}}</td>
        </tr>
        <tr>
        	<th>Date modified</th>
        	<td>{{x.date_modified}}</td>
        </tr>
        <tr>
        	<th>Date issued</th>
        	<td>{{x.date_issued}}</td>
        </tr>
        <tr>
        	<th>Relation</th>
        	<td>{{x.relation}}</td>
        </tr>
        {% if topConcepts %}
        <tr>
            <th>has Top Concepts</th>
            <td>
                {% for x in topConcepts %}
                <li><a href="{{ x.get_absolute_url }}">{{x}}</a></li>
                {% endfor %}
            </td> 
        </tr>
        {% endif %}
        <tr>
            <th>Download</th>
            <td>
            <li><a href="{% url 'vocabs:vocabs-download' %}">RDF/XML</a></li>
            <li><a href="{% url 'vocabs:vocabs-download' %}?format=turtle">Turtle</a></li>
            </td>
        </tr>
        </table>
</div>
{% endfor %}
{% else %}
<a class="btn btn-outline-primary" href="{% url 'vocabs:metadata_create' %}">create Metadata</a>
{% endif %}
</div>
{% endblock %}

vocabs/templates/vocabs/skoscollection_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skoscollection_detail' pk=object.get_prev %}">
                                <i data-feather="chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>skos:Collection</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skoscollection_update' pk=object.id %}">
                                    <i class="feather-32" data-feather="edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skoscollection_delete' pk=object.id %}">
                                    <i class="feather-32" data-feather="trash" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skoscollection_detail' pk=object.get_next %}" style="float:right">
                        <i data-feather="chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <table class="table">
        {% if object.name %}
        <tr>
            <th class="w-25">skos:prefLabel {% if object.label_lang %}@{{object.label_lang}}{% endif %}</th>
            <td>
           {{ object.name }}
            </td>
        </tr>
        {% endif %}
        {% if object.creator %}
         <tr>
            <th class="w-25">dc:creator</th>
            <td>
            {% for creator in object.creator_as_list %}
            <li>{{ creator }}</li>
            {% endfor %}
            </td>
        </tr>
        {% endif %}

        {% if object.skos_note %}
         <tr>
            <th>skos:note{% if object.skos_note_lang %} @{{object.skos_note_lang}}{% endif %}</th>
            <td>{{object.skos_note}}</td>
        </tr>
        {% endif %}

        {% if object.skos_scopenote %}
         <tr>
            <th>skos:scopeNote{% if object.skos_scopenote_lang %} @{{object.skos_scopenote_lang}}{% endif %}</th>
            <td>{{object.skos_scopenote}}</td>
        </tr>
        {% endif %}

        {% if object.skos_changenote %}
         <tr>
            <th>skos:changeNote</th>
            <td>{{object.skos_changenote}}</td>
        </tr>
        {% endif %}

        {% if object.skos_editorialnote %}
         <tr>
            <th>skos:editorialNote</th>
            <td>{{object.skos_editorialnote}}</td>
        </tr>
        {% endif %}

        {% if object.skos_example %}
         <tr>
            <th>skos:example</th>
            <td>{{object.skos_example}}</td>
        </tr>
        {% endif %}

        {% if object.skos_historynote %}
         <tr>
            <th>skos:historyNote</th>
            <td>{{object.skos_historynote}}</td>
        </tr>
        {% endif %}

        {% if object.date_created %}
         <tr>
            <th class="w-25">dct:created</th>
            <td>{{object.date_created}}</td>
        </tr>
        {% endif %}

        {% if object.date_modified %}
         <tr>
            <th class="w-25">dct:modified</th>
            <td>{{object.date_modified}}</td>
        </tr>
        {% endif %}

        {% if object.has_members.all %}
        <tr>
        <th class="w-25">skos:members</th>
        <td>
        {% for x in object.has_members.all %}
            <li>
                <a href="{{ x.get_absolute_url }}">{{ x }}</a>
            </li>
        {% endfor %}
        </td>
        </tr>
        {% endif %}

        </table>  
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skosconcept_filter.html
{% extends "vocabs/generic_list.html" %}
{% block list_title %}Browse SkosConcepts{% endblock %}
{% block create_button %}
{% if user.is_authenticated %}
<div>
    <a class ="btn btn-primary"  href="{% url 'vocabs:skosconcept_create' %}">
        create new concept
    </a>
</div>
{% endif %}
{% endblock %}
{% block reset_button %}
    <a class ="btn btn-outline-secondary" href="{% url 'vocabs:browse_vocabs' %}">reset search</a>
{% endblock %}

vocabs/templates/vocabs/skosconcept_list.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="panel panel-default procustom-panel-list">
        <div class="panel-heading procustom-panel-heading">
            <h1>Concepts </h1>
            <div>
                <a class="btn btn-primary" href="{% url 'vocabs:skosconcept_create' %}" role="button">
                    create concept
                </a>
            </div>
            <br />
        </div>
        <div class="panel-body procustom-panel-body">
            {% for object in object_list %}
                <li>
                    <a href="{% url 'vocabs:skosconcept_detail' pk=object.id %}">{{ object }}</a>
                </li>
           {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skosconceptscheme_list.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="panel panel-default procustom-panel-list">
        <div class="panel-heading procustom-panel-heading">
            <h1>Concept Schemes</h1>
            <div>
                <a class="btn btn-primary" href="{% url 'vocabs:skosconceptscheme_create' %}" role="button">
                    create concept scheme
                </a>
            </div>
            <br />
        </div>
        <div class="panel-body procustom-panel-body">
            {% for object in object_list %}
                <li>
                    <a href="{% url 'vocabs:skosconceptscheme_detail' pk=object.id %}">
                        {{ object }}
                    </a>
                </li>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skoslabel_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skoslabel_detail' pk=object.get_prev %}">
                                
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>Label</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skoslabel_update' pk=object.id %}">
                                    <i class="feather-32" data-feather="edit" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skoslabel_delete' pk=object.id %}">
                                    <i class="feather-32" data-feather="trash" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skoslabel_detail' pk=object.get_next %}" style="float:right">
                        <i data-feather="chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
            <table class="table">
                <tr>
                    <th class="w-25">Label</th>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <th>Label type</th>
                    <td>{{ object.label_type }}</td>
                </tr>
                <tr>
                    <th>IsoCode</th>
                    <td>{{ object.isoCode }}</td>
                </tr>
            </table>
    </div>
</div>
{% endblock %}