bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

infos/urls.py
from django.urls import path
from . import views
from . import special_views

app_name = "infos"
urlpatterns = [
    path("project-team/", special_views.TeamView.as_view(), name="project-team"),
    path(
        "about-the-project/",
        special_views.SpecialAboutView.as_view(),
        name="about-the-project",
    ),
    path("about/", views.AboutTheProjectListView.as_view(), name="about_browse"),
    path(
        "about/detail/<int:pk>",
        views.AboutTheProjectDetailView.as_view(),
        name="about_detail",
    ),
    path("about/create/", views.AboutTheProjectCreate.as_view(), name="about_create"),
    path(
        "about/edit/<int:pk>",
        views.AboutTheProjectUpdate.as_view(),
        name="about_edit",
    ),
    path(
        "about/delete/<int:pk>",
        views.AboutTheProjectDelete.as_view(),
        name="about_delete",
    ),
    path("teammember/", views.TeamMemberListView.as_view(), name="teammember_browse"),
    path(
        "teammember/detail/<int:pk>",
        views.TeamMemberDetailView.as_view(),
        name="teammember_detail",
    ),
    path(
        "teammember/create/",
        views.TeamMemberCreate.as_view(),
        name="teammember_create",
    ),
    path(
        "teammember/edit/<int:pk>",
        views.TeamMemberUpdate.as_view(),
        name="teammember_edit",
    ),
    path(
        "teammember/delete/<int:pk>",
        views.TeamMemberDelete.as_view(),
        name="teammember_delete",
    ),
    path(
        "projectinst/",
        views.ProjectInstListView.as_view(),
        name="projectinst_browse",
    ),
    path(
        "projectinst/detail/<int:pk>",
        views.ProjectInstDetailView.as_view(),
        name="projectinst_detail",
    ),
    path(
        "projectinst/create/",
        views.ProjectInstCreate.as_view(),
        name="projectinst_create",
    ),
    path(
        "projectinst/edit/<int:pk>",
        views.ProjectInstUpdate.as_view(),
        name="projectinst_edit",
    ),
    path(
        "projectinst/delete/<int:pk>",
        views.ProjectInstDelete.as_view(),
        name="projectinst_delete",
    ),
]

p4d/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from vocabs import api_views

router = routers.DefaultRouter()
router.register(r"metadata", api_views.MetadataViewSet)
router.register(r"skoslabels", api_views.SkosLabelViewSet)
router.register(r"skosnamespaces", api_views.SkosNamespaceViewSet)
router.register(r"skosconceptschemes", api_views.SkosConceptSchemeViewSet)
router.register(r"skoscollections", api_views.SkosCollectionViewSet)
router.register(r"skosconcepts", api_views.SkosConceptViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("admin/", admin.site.urls),
    path("archeutils/", include("archeutils.urls", namespace="archeutils")),
    path(
        "filechecker-rdf/",
        include("filechecker.fc_arche_urls", namespace="filechecker-rdf"),
    ),
    path("filechecker/", include("filechecker.urls", namespace="filechecker")),
    path("browsing/", include("browsing.urls", namespace="browsing")),
    path("netvis/", include("netvis.urls", namespace="netvis")),
    path("info/", include("infos.urls", namespace="info")),
    path("archiv/", include("archiv.urls", namespace="archiv")),
    path("qgisapp/", include("qgisapp.urls", namespace="qgisapp")),
    path("vocabs/", include("vocabs.urls", namespace="vocabs")),
    path("vocabs-ac/", include("vocabs.dal_urls", namespace="vocabs-ac")),
    path("", include("webpage.urls", namespace="webpage")),
]

infos/forms.py
# generated by appcreator
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset
from crispy_forms.bootstrap import Accordion, AccordionGroup
from .models import AboutTheProject, TeamMember, ProjectInst


class ProjectInstFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(ProjectInstFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = "genericFilterForm"
        self.form_method = "GET"
        self.helper.form_tag = False
        self.add_input(Submit("Filter", "Search"))
        self.layout = Layout(
            Fieldset(
                "Basic search options", "id", "name", css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup("More", "website", css_id="more"),
            ),
        )


class ProjectInstForm(forms.ModelForm):
    class Meta:
        model = ProjectInst
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ProjectInstForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.add_input(
            Submit("submit", "save"),
        )


class TeamMemberFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(TeamMemberFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = "genericFilterForm"
        self.form_method = "GET"
        self.helper.form_tag = False
        self.add_input(Submit("Filter", "Search"))
        self.layout = Layout(
            Fieldset(
                "Basic search options", "id", "name", css_id="basic_search_fields"
            ),
            Accordion(
                AccordionGroup("More", "website", "role", css_id="more"),
            ),
        )


class TeamMemberForm(forms.ModelForm):
    class Meta:
        model = TeamMember
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(TeamMemberForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.add_input(
            Submit("submit", "save"),
        )


class AboutTheProjectFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(AboutTheProjectFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = "genericFilterForm"
        self.form_method = "GET"
        self.helper.form_tag = False
        self.add_input(Submit("Filter", "Search"))
        self.layout = Layout(
            Fieldset(
                "Basic search options",
                "id",
                "description",
                css_id="basic_search_fields",
            ),
            Accordion(
                AccordionGroup("Authors", "author", css_id="more"),
            ),
        )


class AboutTheProjectForm(forms.ModelForm):
    class Meta:
        model = AboutTheProject
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(AboutTheProjectForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.add_input(
            Submit("submit", "save"),
        )

infos/views.py
# generated by appcreator
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from .filters import AboutTheProjectListFilter, TeamMemberListFilter, ProjectInstListFilter
from .forms import (
    TeamMemberFilterFormHelper,
    TeamMemberForm,
    AboutTheProjectFilterFormHelper,
    AboutTheProjectForm,
    ProjectInstFilterFormHelper,
    ProjectInstForm,
)
from .tables import TeamMemberTable, AboutTheProjectTable, ProjectInstTable
from .models import TeamMember, AboutTheProject, ProjectInst
from browsing.browsing_utils import GenericListView, BaseCreateView, BaseUpdateView


class TeamMemberListView(GenericListView):
    model = TeamMember
    filter_class = TeamMemberListFilter
    formhelper_class = TeamMemberFilterFormHelper
    table_class = TeamMemberTable
    init_columns = [
        "id",
        "description",
    ]


class TeamMemberDetailView(DetailView):
    model = TeamMember
    template_name = "browsing/generic_detail.html"


class TeamMemberCreate(BaseCreateView):
    model = TeamMember
    form_class = TeamMemberForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TeamMemberCreate, self).dispatch(*args, **kwargs)


class TeamMemberUpdate(BaseUpdateView):
    model = TeamMember
    form_class = TeamMemberForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TeamMemberUpdate, self).dispatch(*args, **kwargs)


class TeamMemberDelete(DeleteView):
    model = TeamMember
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("info:teammember_browse")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TeamMemberDelete, self).dispatch(*args, **kwargs)


class AboutTheProjectListView(GenericListView):
    model = AboutTheProject
    filter_class = AboutTheProjectListFilter
    formhelper_class = AboutTheProjectFilterFormHelper
    table_class = AboutTheProjectTable
    init_columns = [
        "id",
        "description",
    ]


class AboutTheProjectDetailView(DetailView):
    model = AboutTheProject
    template_name = "browsing/generic_detail.html"


class AboutTheProjectCreate(BaseCreateView):
    model = AboutTheProject
    form_class = AboutTheProjectForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AboutTheProjectCreate, self).dispatch(*args, **kwargs)


class AboutTheProjectUpdate(BaseUpdateView):
    model = AboutTheProject
    form_class = AboutTheProjectForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AboutTheProjectUpdate, self).dispatch(*args, **kwargs)


class AboutTheProjectDelete(DeleteView):
    model = AboutTheProject
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("info:about_browse")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AboutTheProjectDelete, self).dispatch(*args, **kwargs)


class ProjectInstListView(GenericListView):
    model = ProjectInst
    filter_class = ProjectInstListFilter
    formhelper_class = ProjectInstFilterFormHelper
    table_class = ProjectInstTable
    init_columns = [
        "id",
        "description",
    ]


class ProjectInstDetailView(DetailView):
    model = ProjectInst
    template_name = "browsing/generic_detail.html"


class ProjectInstCreate(BaseCreateView):
    model = ProjectInst
    form_class = ProjectInstForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectInstCreate, self).dispatch(*args, **kwargs)


class ProjectInstUpdate(BaseUpdateView):
    model = ProjectInst
    form_class = ProjectInstForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectInstUpdate, self).dispatch(*args, **kwargs)


class ProjectInstDelete(DeleteView):
    model = ProjectInst
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("info:projectinst_browse")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectInstDelete, self).dispatch(*args, **kwargs)

infos/templates/infos/about.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %}{{ object.name }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header" style="text-align: center">
                <h1>{{ object.title }}</h1>
                {% if object.subtitle %}
                    <h2>{{ object.subtitle}}</h2>
                {% endif %}
            </div>
            <div class="card-body">
                {{ object.description|safe}}
            </div>
            <div class="card-footer" style="text-align: center">
                <p>
                    <small>{{ object.author }}</small>
                    <br />
                    <a href="{{ object.github }}">{{ object.github}}</a>
                    {% if user.is_authenticated and object.get_edit_url %}
                        <br />
                        <a href="{{ object.get_edit_url }}">
                            <i class="feather-32" data-feather="edit" title="edit"></i>
                        </a>
                    {% elif user.is_authenticated %}
                        <br />
                        <small>Data fetched from metadata file, better to create an <a href="{% url 'infos:about_create' %}">AboutTheProject</a> object</small>
                    {% endif %}
                </p>
            </div>

        </div>
    </div>
{% endblock %}

infos/templates/infos/team.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %}{{ object.name }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header" style="text-align: center">
                <h1>Team</h1>
            </div>
            <div class="card-body">
                {% if objects %}
                    {% for object in objects %}
                        <div>
                            <h2>{{ object.name}}</h2>
                            <h3>{{ object.role }}</h3>
                            <p>
                                {{ object.description }}
                            </p>
                            <p>
                                <a href="{{ object.website}}">{{ object.website }}</a>
                            </p>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>
                        No TeamMemeber objects have been created yet.
                        {% if user.is_authenticated %}
                            <strong>
                                go <a href="{% url 'infos:teammember_browse' %}">create</a> some
                            </strong>
                        {% endif %}
                    </p>
                {% endif %}
            </div>
            <div class="card-footer" style="text-align: center">
                <p>
                    {% if user.is_authenticated %}
                        <br />
                        <small>Data is fetch from <a href="{% url 'infos:teammember_browse' %}">TeamMember</a> object</small>
                    {% endif %}
                </p>
            </div>

        </div>
    </div>
{% endblock %}